### ISSUE TITLE
RunAzimuth error, Kidney dataset

### ISSUE THREAD

**Issue by reshu23** [satijalab/azimuth#161] opened 2023-07-06 08:09 UTC
Dear Team,

I have successfully executed RunAzimuth with fetusref on my dataset(seurat object). But when I used Kidneyref, it is giving following error:

reference rownames detected HUMAN with id type Gene.name
Normalizing query using reference SCT model
Warning: No layers found matching search pattern provided
Warning: 698 features of the features specified were not present in both the reference query assays.
Continuing with remaining 2340 features.
Projecting cell embeddings
Error in ProjectCellEmbeddings.Seurat(reference = reference, reduction = reference.reduction,  :
  Given reference assay (refAssay) doesn't contain a reference SCT model.
Calls: RunAzimuth ... ProjectCellEmbeddings -> ProjectCellEmbeddings.Seurat
Execution halted

Thank you.

**Comment by schmeing** [comment] 2023-12-08 15:37
Dear Team,

Has this been looked at? I have exactly the same issue with a fresh installation of Seurat and Azimuth:

```
R version 4.3.0 (2023-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Fedora 33 (Container Image)

Matrix products: default
BLAS/LAPACK: /apps/rocs/2020.08/cascadelake/software/OpenBLAS/0.3.9-GCC-9.3.0/lib/libopenblas_skylakexp-r0.3.9.so;  LAPACK version 3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/Zurich
tzcode source: system (glibc)

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] kidneyref.SeuratData_1.0.1     bonemarrowref.SeuratData_1.0.0 pbmcref.SeuratData_1.0.0       qs_0.25.7                     
 [5] viridis_0.6.4                  viridisLite_0.4.2              patchwork_1.1.3                ggrepel_0.9.4                 
 [9] tibble_3.2.1                   stringr_1.5.1                  tidyr_1.3.0                    dplyr_1.1.4                   
[13] readr_2.1.4                    Azimuth_0.5.0                  shinyBS_0.61.1                 Seurat_5.0.1                  
[17] SeuratObject_5.0.1             sp_2.1-2                       symphony_0.1.1                 scDblFinder_1.16.0            
[21] edgeR_4.0.2                    limma_3.58.1                   bluster_1.12.0                 scran_1.30.0                  
[25] scater_1.30.1                  ggplot2_3.4.4                  scuttle_1.12.0                 mumosa_1.10.0                 
[29] SingleCellExperiment_1.24.0    SummarizedExperiment_1.32.0    Biobase_2.62.0                 GenomicRanges_1.54.1          
[33] GenomeInfoDb_1.38.1            IRanges_2.36.0                 S4Vectors_0.40.2               BiocGenerics_0.48.1           
[37] MatrixGenerics_1.14.0          matrixStats_1.1.0             

loaded via a namespace (and not attached):
  [1] R.methodsS3_1.8.2                 progress_1.2.3                    poweRlaw_0.70.6                  
  [4] goftest_1.2-3                     DT_0.30                           Biostrings_2.70.1                
  [7] vctrs_0.6.5                       spatstat.random_3.2-2             RApiSerialize_0.1.2              
 [10] digest_0.6.33                     png_0.1-8                         deldir_2.0-2                     
 [13] parallelly_1.36.0                 batchelor_1.18.0                  MASS_7.3-60                      
 [16] Signac_1.12.0                     reshape2_1.4.4                    httpuv_1.6.13                    
 [19] withr_2.5.2                       xfun_0.41                         ellipsis_0.3.2                   
 [22] survival_3.5-7                    EnsDb.Hsapiens.v86_2.99.0         memoise_2.0.1                    
 [25] ggbeeswarm_0.7.2                  zoo_1.8-12                        gtools_3.9.5                     
 [28] pbapply_1.7-2                     R.oo_1.25.0                       prettyunits_1.2.0                
 [31] KEGGREST_1.42.0                   promises_1.2.1                    httr_1.4.7                       
 [34] restfulr_0.0.15                   globals_0.16.2                    fitdistrplus_1.1-11              
 [37] rhdf5filters_1.14.1               stringfish_0.16.0                 rhdf5_2.46.1                     
 [40] rstudioapi_0.15.0                 miniUI_0.1.1.1                    generics_0.1.3                   
 [43] curl_5.1.0                        zlibbioc_1.48.0                   ScaledMatrix_1.10.0              
 [46] polyclip_1.10-6                   GenomeInfoDbData_1.2.11           SparseArray_1.2.2                
 [49] xtable_1.8-4                      pracma_2.4.4                      S4Arrays_1.2.0                   
 [52] BiocFileCache_2.10.1              hms_1.1.3                         irlba_2.3.5.1                    
 [55] colorspace_2.1-0                  filelock_1.0.2                    hdf5r_1.3.8                      
 [58] ROCR_1.0-11                       reticulate_1.34.0                 spatstat.data_3.0-3              
 [61] magrittr_2.0.3                    lmtest_0.9-40                     later_1.3.2                      
 [64] lattice_0.22-5                    spatstat.geom_3.2-7               future.apply_1.11.0              
 [67] scattermore_1.2                   XML_3.99-0.16                     cowplot_1.1.1                    
 [70] RcppAnnoy_0.0.21                  pillar_1.9.0                      nlme_3.1-164                     
 [73] caTools_1.18.2                    compiler_4.3.0                    beachmat_2.18.0                  
 [76] RSpectra_0.16-1                   stringi_1.8.2                     tensor_1.5                       
 [79] GenomicAlignments_1.38.0          plyr_1.8.9                        crayon_1.5.2                     
 [82] abind_1.4-5                       BiocIO_1.12.0                     googledrive_2.1.1                
 [85] locfit_1.5-9.8                    bit_4.0.5                         fastmatch_1.1-4                  
 [88] codetools_0.2-19                  BiocSingular_1.18.0               SeuratData_0.2.2.9001            
 [91] plotly_4.10.3                     mime_0.12                         splines_4.3.0                    
 [94] Rcpp_1.0.11                       fastDummies_1.7.3                 dbplyr_2.4.0                     
 [97] sparseMatrixStats_1.14.0          cellranger_1.1.0                  knitr_1.45                       
[100] blob_1.2.4                        utf8_1.2.4                        seqLogo_1.68.0                   
[103] AnnotationFilter_1.26.0           fs_1.6.3                          listenv_0.9.0                    
[106] DelayedMatrixStats_1.24.0         Matrix_1.6-4                      statmod_1.5.0                    
[109] tzdb_0.4.0                        pkgconfig_2.0.3                   tools_4.3.0                      
[112] cachem_1.0.8                      RSQLite_2.3.4                     DBI_1.1.3                        
[115] fastmap_1.1.1                     scales_1.3.0                      grid_4.3.0                       
[118] ica_1.0-3                         shinydashboard_0.7.2              Rsamtools_2.18.0                 
[121] BiocManager_1.30.22               dotCall64_1.1-1                   RANN_2.6.1                       
[124] farver_2.1.1                      yaml_2.3.7                        rtracklayer_1.62.0               
[127] cli_3.6.1                         purrr_1.0.2                       leiden_0.4.3.1                   
[130] lifecycle_1.0.4                   uwot_0.1.16                       presto_1.0.0                     
[133] BSgenome.Hsapiens.UCSC.hg38_1.4.5 BiocParallel_1.36.0               annotate_1.80.0                  
[136] gtable_0.3.4                      rjson_0.2.21                      ggridges_0.5.4                   
[139] progressr_0.14.0                  parallel_4.3.0                    jsonlite_1.8.8                   
[142] RcppHNSW_0.5.0                    TFBSTools_1.40.0                  bitops_1.0-7                     
[145] bit64_4.0.5                       xgboost_1.7.6.1                   Rtsne_0.17                       
[148] spatstat.utils_3.0-4              BiocNeighbors_1.20.0              RcppParallel_5.1.7               
[151] CNEr_1.38.0                       metapod_1.10.0                    dqrng_0.3.2                      
[154] shinyjs_2.1.0                     SeuratDisk_0.0.0.9021             R.utils_2.12.3                   
[157] lazyeval_0.2.2                    shiny_1.8.0                       htmltools_0.5.7                  
[160] GO.db_3.18.0                      sctransform_0.4.1                 rappdirs_0.3.3                   
[163] ensembldb_2.26.0                  glue_1.6.2                        TFMPvalue_0.0.9                  
[166] spam_2.10-0                       googlesheets4_1.1.1               ResidualMatrix_1.12.0            
[169] XVector_0.42.0                    RCurl_1.98-1.13                   BSgenome_1.70.1                  
[172] gridExtra_2.3                     JASPAR2020_0.99.10                igraph_1.5.1                     
[175] R6_2.5.1                          labeling_0.4.3                    RcppRoll_0.3.0                   
[178] GenomicFeatures_1.54.1            cluster_2.1.6                     Rhdf5lib_1.24.0                  
[181] gargle_1.5.2                      DirichletMultinomial_1.42.0       DelayedArray_0.28.0              
[184] tidyselect_1.2.0                  vipor_0.4.5                       ProtGenerics_1.34.0              
[187] xml2_1.3.6                        AnnotationDbi_1.64.1              future_1.33.0                    
[190] rsvd_1.0.5                        munsell_0.5.0                     KernSmooth_2.23-22               
[193] data.table_1.14.8                 htmlwidgets_1.6.4                 RColorBrewer_1.1-3               
[196] biomaRt_2.58.0                    rlang_1.1.2                       spatstat.sparse_3.0-3            
[199] spatstat.explore_3.2-5            fansi_1.0.6                       beeswarm_0.4.0
```

The other references work.

**Comment by alexvnesta** [comment] 2024-01-18 20:56
I am bumping because I have the same issue here.

I tried manually downloading the dataset. Unfortunately, the object was not processed using SCTransform and the authors are missing the original count data in the Seurat Object that Azimuth downloads. I think this may be an issues for the authors of the dataset to fix on their end?

Steps to reproduce:

```
library(Seurat)
library(SeuratData)
data("pbmc_small")
pbmc_small
Azimuth::RunAzimuth(query = pbmc_small,
                    reference = "kidneyref")
```

```
> Azimuth::RunAzimuth(query = pbmc_small,
+                                     reference = "kidneyref")
Warning: Overwriting miscellanous data for model
Warning: Adding a dimensional reduction (refUMAP) without the associated assay being present
Warning: Adding a dimensional reduction (refUMAP) without the associated assay being present
detected inputs from HUMAN with id type Gene.name
reference rownames detected HUMAN with id type Gene.name
Normalizing query using reference SCT model
Warning: 2911 features of the features specified were not present in both the reference query assays. 
Continuing with remaining 127 features.
Projecting cell embeddings
Error in ProjectCellEmbeddings.Seurat(reference = reference, reduction = reference.reduction,  : 
  Given reference assay (refAssay) doesn't contain a reference SCT model.
```

**Comment by carlapou** [comment] 2024-02-06 12:50
Same issue. 
It indeed works super smoothly with fetusref but I get the same SCT error with kidneyref. I hope this gets resolved soon.

**Comment by Gesmira** [comment] 2024-02-22 22:53
Hi, 
Thank you for bringing this to our attention. We had to update the data structure of the kidney reference and it is now fixed. 
You can access it by reinstalling the kidney reference from SeuratData and then running Azimuth:
```
InstallData("kidneyref", force.reinstall = T)
obj <- RunAzimuth(obj, "kidneyref")
```
The updated object is also available on Zenodo.

**Closed by Gesmira** 2024-02-22 22:53 UTC
