### ISSUE TITLE
Error in .local(x, na.rm, dims, ...) :    object 'CRsparse_colSums' not found error from RunAzimuth() 

### ISSUE THREAD

**Issue by annstrange** [satijalab/azimuth#192] opened 2023-11-21 00:19 UTC
After upgrading Seurat, SeuratData, and Azimuth to the most recent versions, then when I load Azimuth with library(Azimuth) I first get a warning that 
Registered S3 method overwritten by 'SeuratDisk':
  method            from  
  as.sparse.H5Group Seurat

and then a number of methods stop working including Seurat::LoadNanostring(), Azimuth::RunAzimuth(), and Seurat::SCTransform().  The error does not happen until I've loaded library(Azimuth).  These were all working before I updated to Seurat v5, but Azimuth seems to be breaking things by insisting on overwriting the as.sparse.H5Group method. 

Example code: 
> seurat_obj <- Azimuth::RunAzimuth(seurat_obj, reference="./lungref.SeuratData/inst/azimuth")
Warning: Overwriting miscellanous data for model
Warning: Adding a dimensional reduction (refUMAP) without the associated assay being present
detected inputs from HUMAN with id type Gene.name
reference rownames detected HUMAN with id type Gene.name
Error in .local(x, na.rm, dims, ...) : 
  object 'CRsparse_colSums' not found

Steps to reproduce:
1.  Install Seurat v5 as instructed here: https://satijalab.org/seurat/articles/install_v5
2.  `library(Seurat)`
3. for some basic Seurat object you have already, load it as obj
4. `obj <- SCTransform(obj, assay="RNA")` # it'll work
5. `library(Azimuth)`
6. `obj <- SCTransform(obj, assay="RNA")` # it'll fail with CRsparse_colSums not found error.
7. `obj <- RunAzimuth(obj, <whatever parameters>)` # it'll fail too.

> sessionInfo()
R version 4.3.2 (2023-10-31)
Platform: x86_64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.1.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Denver
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Azimuth_0.5.0         shinyBS_0.61.1        dplyr_1.1.4           BPCells_0.1.0        
[5] Seurat_5.0.1          ifnb.SeuratData_3.1.0 SeuratData_0.2.2.9001 SeuratObject_5.0.1   
[9] sp_2.1-1             

loaded via a namespace (and not attached):
  [1] fs_1.6.3                          ProtGenerics_1.34.0               matrixStats_1.1.0                
  [4] spatstat.sparse_3.0-3             bitops_1.0-7                      DirichletMultinomial_1.44.0      
  [7] TFBSTools_1.40.0                  httr_1.4.7                        RColorBrewer_1.1-3               
 [10] tools_4.3.2                       sctransform_0.4.1                 utf8_1.2.4                       
 [13] R6_2.5.1                          DT_0.30                           lazyeval_0.2.2                   
 [16] uwot_0.1.16                       rhdf5filters_1.14.1               withr_2.5.2                      
 [19] prettyunits_1.2.0                 gridExtra_2.3                     progressr_0.14.0                 
 [22] cli_3.6.1                         Biobase_2.62.0                    spatstat.explore_3.2-5           
 [25] fastDummies_1.7.3                 EnsDb.Hsapiens.v86_2.99.0         shinyjs_2.1.0                    
 [28] spatstat.data_3.0-3               readr_2.1.4                       ggridges_0.5.4                   
 [31] pbapply_1.7-2                     Rsamtools_2.18.0                  R.utils_2.12.3                   
 [34] parallelly_1.36.0                 BSgenome_1.70.1                   rstudioapi_0.15.0                
 [37] RSQLite_2.3.3                     generics_0.1.3                    BiocIO_1.12.0                    
 [40] gtools_3.9.4                      ica_1.0-3                         spatstat.random_3.2-1            
 [43] googlesheets4_1.1.1               GO.db_3.18.0                      Matrix_1.6-3                     
 [46] fansi_1.0.5                       S4Vectors_0.40.1                  abind_1.4-5                      
 [49] R.methodsS3_1.8.2                 lifecycle_1.0.4                   yaml_2.3.7                       
 [52] SummarizedExperiment_1.32.0       rhdf5_2.46.0                      SparseArray_1.2.2                
 [55] BiocFileCache_2.10.1              Rtsne_0.16                        grid_4.3.2                       
 [58] blob_1.2.4                        promises_1.2.1                    shinydashboard_0.7.2             
 [61] crayon_1.5.2                      miniUI_0.1.1.1                    lattice_0.22-5                   
 [64] cowplot_1.1.1                     GenomicFeatures_1.54.1            annotate_1.80.0                  
 [67] KEGGREST_1.42.0                   pillar_1.9.0                      GenomicRanges_1.54.1             
 [70] rjson_0.2.21                      future.apply_1.11.0               codetools_0.2-19                 
 [73] fastmatch_1.1-4                   leiden_0.4.3.1                    glue_1.6.2                       
 [76] data.table_1.14.8                 vctrs_0.6.4                       png_0.1-8                        
 [79] spam_2.10-0                       cellranger_1.1.0                  gtable_0.3.4                     
 [82] poweRlaw_0.70.6                   cachem_1.0.8                      Signac_1.12.0                    
 [85] S4Arrays_1.2.0                    mime_0.12                         pracma_2.4.4                     
 [88] survival_3.5-7                    gargle_1.5.2                      RcppRoll_0.3.0                   
 [91] ellipsis_0.3.2                    fitdistrplus_1.1-11               ROCR_1.0-11                      
 [94] nlme_3.1-163                      bit64_4.0.5                       progress_1.2.2                   
 [97] filelock_1.0.2                    RcppAnnoy_0.0.21                  GenomeInfoDb_1.38.1              
[100] irlba_2.3.5.1                     KernSmooth_2.23-22                SeuratDisk_0.0.0.9021            
[103] colorspace_2.1-0                  seqLogo_1.68.0                    BiocGenerics_0.48.1              
[106] DBI_1.1.3                         tidyselect_1.2.0                  bit_4.0.5                        
[109] compiler_4.3.2                    curl_5.1.0                        hdf5r_1.3.8                      
[112] xml2_1.3.5                        DelayedArray_0.28.0               plotly_4.10.3                    
[115] rtracklayer_1.62.0                scales_1.2.1                      caTools_1.18.2                   
[118] lmtest_0.9-40                     rappdirs_0.3.3                    stringr_1.5.1                    
[121] digest_0.6.33                     goftest_1.2-3                     presto_1.0.0                     
[124] spatstat.utils_3.0-4              XVector_0.42.0                    htmltools_0.5.7                  
[127] pkgconfig_2.0.3                   MatrixGenerics_1.14.0             dbplyr_2.4.0                     
[130] fastmap_1.1.1                     ensembldb_2.26.0                  rlang_1.1.2                      
[133] htmlwidgets_1.6.2                 shiny_1.8.0                       zoo_1.8-12                       
[136] jsonlite_1.8.7                    BiocParallel_1.36.0               R.oo_1.25.0                      
[139] RCurl_1.98-1.13                   magrittr_2.0.3                    GenomeInfoDbData_1.2.11          
[142] dotCall64_1.1-0                   patchwork_1.1.3                   Rhdf5lib_1.24.0                  
[145] munsell_0.5.0                     Rcpp_1.0.11                       reticulate_1.34.0                
[148] stringi_1.8.1                     zlibbioc_1.48.0                   MASS_7.3-60                      
[151] plyr_1.8.9                        parallel_4.3.2                    listenv_0.9.0                    
[154] ggrepel_0.9.4                     deldir_1.0-9                      CNEr_1.38.0                      
[157] Biostrings_2.70.1                 splines_4.3.2                     tensor_1.5                       
[160] hms_1.1.3                         BSgenome.Hsapiens.UCSC.hg38_1.4.5 igraph_1.5.1                     
[163] spatstat.geom_3.2-7               RcppHNSW_0.5.0                    reshape2_1.4.4                   
[166] biomaRt_2.58.0                    stats4_4.3.2                      TFMPvalue_0.0.9                  
[169] XML_3.99-0.15                     JASPAR2020_0.99.10                tzdb_0.4.0                       
[172] httpuv_1.6.12                     RANN_2.6.1                        tidyr_1.3.0                      
[175] purrr_1.0.2                       polyclip_1.10-6                   future_1.33.0                    
[178] scattermore_1.2                   ggplot2_3.4.4                     xtable_1.8-4                     
[181] restfulr_0.0.15                   AnnotationFilter_1.26.0           RSpectra_0.16-1                  
[184] later_1.3.1                       googledrive_2.1.1                 viridisLite_0.4.2                
[187] tibble_3.2.1                      memoise_2.0.1                     AnnotationDbi_1.64.1             
[190] GenomicAlignments_1.38.0          IRanges_2.36.0                    cluster_2.1.4                    
[193] globals_0.16.2

**Comment by ian-coccimiglio** [comment] 2023-11-21 23:32
I'm getting the same issue, setup is on Windows 10 with Seurat v5 and updated Azimuth.

**Comment by Niubile001** [comment] 2023-11-25 04:53
> After upgrading Seurat, SeuratData, and Azimuth to the most recent versions, then when I load Azimuth with library(Azimuth) I first get a warning that Registered S3 method overwritten by 'SeuratDisk': method from as.sparse.H5Group Seurat
> 
> and then a number of methods stop working including Seurat::LoadNanostring(), Azimuth::RunAzimuth(), and Seurat::SCTransform(). The error does not happen until I've loaded library(Azimuth). These were all working before I updated to Seurat v5, but Azimuth seems to be breaking things by insisting on overwriting the as.sparse.H5Group method.
> 
> Example code:
> 
> > seurat_obj <- Azimuth::RunAzimuth(seurat_obj, reference="./lungref.SeuratData/inst/azimuth")
> > Warning: Overwriting miscellanous data for model
> > Warning: Adding a dimensional reduction (refUMAP) without the associated assay being present
> > detected inputs from HUMAN with id type Gene.name
> > reference rownames detected HUMAN with id type Gene.name
> > Error in .local(x, na.rm, dims, ...) :
> > object 'CRsparse_colSums' not found
> 
> Steps to reproduce:
> 
> 1. Install Seurat v5 as instructed here: https://satijalab.org/seurat/articles/install_v5
> 2. `library(Seurat)`
> 3. for some basic Seurat object you have already, load it as obj
> 4. `obj <- SCTransform(obj, assay="RNA")` # it'll work
> 5. `library(Azimuth)`
> 6. `obj <- SCTransform(obj, assay="RNA")` # it'll fail with CRsparse_colSums not found error.
> 7. `obj <- RunAzimuth(obj, <whatever parameters>)` # it'll fail too.
> 
> > sessionInfo()
> > R version 4.3.2 (2023-10-31)
> > Platform: x86_64-apple-darwin20 (64-bit)
> > Running under: macOS Sonoma 14.1.1
> 
> Matrix products: default BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib LAPACK: /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/lib/libRlapack.dylib; LAPACK version 3.11.0
> 
> locale: [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> time zone: America/Denver tzcode source: internal
> 
> attached base packages: [1] stats graphics grDevices utils datasets methods base
> 
> other attached packages: [1] Azimuth_0.5.0 shinyBS_0.61.1 dplyr_1.1.4 BPCells_0.1.0 [5] Seurat_5.0.1 ifnb.SeuratData_3.1.0 SeuratData_0.2.2.9001 SeuratObject_5.0.1 [9] sp_2.1-1
> 
> loaded via a namespace (and not attached): [1] fs_1.6.3 ProtGenerics_1.34.0 matrixStats_1.1.0 [4] spatstat.sparse_3.0-3 bitops_1.0-7 DirichletMultinomial_1.44.0 [7] TFBSTools_1.40.0 httr_1.4.7 RColorBrewer_1.1-3 [10] tools_4.3.2 sctransform_0.4.1 utf8_1.2.4 [13] R6_2.5.1 DT_0.30 lazyeval_0.2.2 [16] uwot_0.1.16 rhdf5filters_1.14.1 withr_2.5.2 [19] prettyunits_1.2.0 gridExtra_2.3 progressr_0.14.0 [22] cli_3.6.1 Biobase_2.62.0 spatstat.explore_3.2-5 [25] fastDummies_1.7.3 EnsDb.Hsapiens.v86_2.99.0 shinyjs_2.1.0 [28] spatstat.data_3.0-3 readr_2.1.4 ggridges_0.5.4 [31] pbapply_1.7-2 Rsamtools_2.18.0 R.utils_2.12.3 [34] parallelly_1.36.0 BSgenome_1.70.1 rstudioapi_0.15.0 [37] RSQLite_2.3.3 generics_0.1.3 BiocIO_1.12.0 [40] gtools_3.9.4 ica_1.0-3 spatstat.random_3.2-1 [43] googlesheets4_1.1.1 GO.db_3.18.0 Matrix_1.6-3 [46] fansi_1.0.5 S4Vectors_0.40.1 abind_1.4-5 [49] R.methodsS3_1.8.2 lifecycle_1.0.4 yaml_2.3.7 [52] SummarizedExperiment_1.32.0 rhdf5_2.46.0 SparseArray_1.2.2 [55] BiocFileCache_2.10.1 Rtsne_0.16 grid_4.3.2 [58] blob_1.2.4 promises_1.2.1 shinydashboard_0.7.2 [61] crayon_1.5.2 miniUI_0.1.1.1 lattice_0.22-5 [64] cowplot_1.1.1 GenomicFeatures_1.54.1 annotate_1.80.0 [67] KEGGREST_1.42.0 pillar_1.9.0 GenomicRanges_1.54.1 [70] rjson_0.2.21 future.apply_1.11.0 codetools_0.2-19 [73] fastmatch_1.1-4 leiden_0.4.3.1 glue_1.6.2 [76] data.table_1.14.8 vctrs_0.6.4 png_0.1-8 [79] spam_2.10-0 cellranger_1.1.0 gtable_0.3.4 [82] poweRlaw_0.70.6 cachem_1.0.8 Signac_1.12.0 [85] S4Arrays_1.2.0 mime_0.12 pracma_2.4.4 [88] survival_3.5-7 gargle_1.5.2 RcppRoll_0.3.0 [91] ellipsis_0.3.2 fitdistrplus_1.1-11 ROCR_1.0-11 [94] nlme_3.1-163 bit64_4.0.5 progress_1.2.2 [97] filelock_1.0.2 RcppAnnoy_0.0.21 GenomeInfoDb_1.38.1 [100] irlba_2.3.5.1 KernSmooth_2.23-22 SeuratDisk_0.0.0.9021 [103] colorspace_2.1-0 seqLogo_1.68.0 BiocGenerics_0.48.1 [106] DBI_1.1.3 tidyselect_1.2.0 bit_4.0.5 [109] compiler_4.3.2 curl_5.1.0 hdf5r_1.3.8 [112] xml2_1.3.5 DelayedArray_0.28.0 plotly_4.10.3 [115] rtracklayer_1.62.0 scales_1.2.1 caTools_1.18.2 [118] lmtest_0.9-40 rappdirs_0.3.3 stringr_1.5.1 [121] digest_0.6.33 goftest_1.2-3 presto_1.0.0 [124] spatstat.utils_3.0-4 XVector_0.42.0 htmltools_0.5.7 [127] pkgconfig_2.0.3 MatrixGenerics_1.14.0 dbplyr_2.4.0 [130] fastmap_1.1.1 ensembldb_2.26.0 rlang_1.1.2 [133] htmlwidgets_1.6.2 shiny_1.8.0 zoo_1.8-12 [136] jsonlite_1.8.7 BiocParallel_1.36.0 R.oo_1.25.0 [139] RCurl_1.98-1.13 magrittr_2.0.3 GenomeInfoDbData_1.2.11 [142] dotCall64_1.1-0 patchwork_1.1.3 Rhdf5lib_1.24.0 [145] munsell_0.5.0 Rcpp_1.0.11 reticulate_1.34.0 [148] stringi_1.8.1 zlibbioc_1.48.0 MASS_7.3-60 [151] plyr_1.8.9 parallel_4.3.2 listenv_0.9.0 [154] ggrepel_0.9.4 deldir_1.0-9 CNEr_1.38.0 [157] Biostrings_2.70.1 splines_4.3.2 tensor_1.5 [160] hms_1.1.3 BSgenome.Hsapiens.UCSC.hg38_1.4.5 igraph_1.5.1 [163] spatstat.geom_3.2-7 RcppHNSW_0.5.0 reshape2_1.4.4 [166] biomaRt_2.58.0 stats4_4.3.2 TFMPvalue_0.0.9 [169] XML_3.99-0.15 JASPAR2020_0.99.10 tzdb_0.4.0 [172] httpuv_1.6.12 RANN_2.6.1 tidyr_1.3.0 [175] purrr_1.0.2 polyclip_1.10-6 future_1.33.0 [178] scattermore_1.2 ggplot2_3.4.4 xtable_1.8-4 [181] restfulr_0.0.15 AnnotationFilter_1.26.0 RSpectra_0.16-1 [184] later_1.3.1 googledrive_2.1.1 viridisLite_0.4.2 [187] tibble_3.2.1 memoise_2.0.1 AnnotationDbi_1.64.1 [190] GenomicAlignments_1.38.0 IRanges_2.36.0 cluster_2.1.4 [193] globals_0.16.2

Try reinstall irlba package may be helpful. It seems to be a conflict raised by latest Matrix (1.6.3) package.

**Comment by annstrange** [comment] 2023-11-25 06:22
thanks for the quick response!  However, after doing that, I'm still getting the same issue.

**Comment by Gesmira** [comment] 2023-11-29 18:05
Thank you for the reproducible example, this was also reported [here](https://github.com/satijalab/seurat/issues/8094#issuecomment-1831530431). 
`RunAzimuth` actually worked fine for me and I only got your error message with SCTransform. I don't think this is related to overwriting the as.sparse.H5Group method, as that has always been done. It seems to specifically be an issue with running `colSums()` on a sparse matrix due to a conflict with TFBSTools that is now loaded with Azimuth for Azimuth ATAC. 
```
> head(colSums(obj[["RNA"]]$counts))
# this works
> head(TFBSTools::colSums(obj[["RNA"]]$counts))
Error in .local(x, na.rm, dims, ...) : 
  object 'CRsparse_colSums' not found
  ```
  
Specifically, this is only an issue if you have `Matrix 1.6-3`. `TFBSTools::colSums` runs fine if I have an older Matrix version. Looking into this now and if it's even fixable on our end or which packages we should reach out to. Will update here.

**Comment by Gesmira** [comment] 2023-12-08 20:41
Hi, 
A solution is detailed in Seurat: https://github.com/satijalab/seurat/issues/8089#issuecomment-1847816493

- Ensure you have R version 4.3 or update to it.
- In a fresh R session, update Bioconductor with the following call:
```
BiocManager::install(version = "3.18")
```
- When prompted if you would like to update all packages, say yes. This will then update a series of Bioconductor packages which may take up to an hour.
- At this point, the issue should be fixed. Let us know if you continue to encounter problems.

**Closed as completed by Gesmira** 2023-12-08 20:41 UTC

**Comment by JarneBelien** [comment] 2023-12-12 08:53
Dear @Gesmira, 

I have done the above fix but I keep getting this error when I run `RunAzimuth`: 

`Error in .local(x, na.rm, dims, ...) : 
  object 'CRsparse_colSums' not found`

My R version is 4.3.1 and I ran the `BiocManager::install(version = "3.18")` command as suggested above. 

I also saw in another thread that a possible fix might be to unload Azimuth, however as I am trying to run the `RunAzimuth` command this is of course not an option. Might it still be due to some other dependency conflicts?

Do you have any other fix suggestions?

**Comment by Gesmira** [comment] 2023-12-12 15:47
Hi @JarneBelien , 
I'm afraid I can't reproduce this. Did you restart your R session before updating the packages? 
If you're still experiencing the error, can you include the full output of `sessionInfo()`?

**Comment by JarneBelien** [comment] 2023-12-12 15:53
Yes, I did restart the R session before the update. I tried again and get the same error. My session info is as follows:

`R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default


locale:
[1] LC_COLLATE=Dutch_Belgium.utf8  LC_CTYPE=Dutch_Belgium.utf8    LC_MONETARY=Dutch_Belgium.utf8
[4] LC_NUMERIC=C                   LC_TIME=Dutch_Belgium.utf8    

time zone: Europe/Brussels
tzcode source: internal

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] Azimuth_0.5.0         shinyBS_0.61.1        writexl_1.4.2         viridis_0.6.4         viridisLite_0.4.2    
 [6] showtext_0.9-6        showtextdb_3.0        sysfonts_0.8.8        Seurat_5.0.1          RColorBrewer_1.1-3   
[11] ggplot2_3.4.4         FSA_0.9.5             dplyr_1.1.4           ComplexHeatmap_2.18.0 SeuratObject_5.0.1   
[16] sp_2.1-2             

loaded via a namespace (and not attached):
  [1] fs_1.6.3                          ProtGenerics_1.34.0               matrixStats_1.2.0                
  [4] spatstat.sparse_3.0-3             bitops_1.0-7                      DirichletMultinomial_1.44.0      
  [7] TFBSTools_1.40.0                  httr_1.4.7                        doParallel_1.0.17                
 [10] tools_4.3.1                       sctransform_0.4.1                 utf8_1.2.4                       
 [13] R6_2.5.1                          DT_0.31                           lazyeval_0.2.2                   
 [16] uwot_0.1.16                       rhdf5filters_1.14.1               GetoptLong_1.0.5                 
 [19] withr_2.5.2                       prettyunits_1.2.0                 gridExtra_2.3                    
 [22] progressr_0.14.0                  cli_3.6.2                         Biobase_2.62.0                   
 [25] spatstat.explore_3.2-5            fastDummies_1.7.3                 EnsDb.Hsapiens.v86_2.99.0        
 [28] shinyjs_2.1.0                     labeling_0.4.3                    spatstat.data_3.0-3              
 [31] readr_2.1.4                       ggridges_0.5.4                    pbapply_1.7-2                    
 [34] Rsamtools_2.18.0                  R.utils_2.12.3                    parallelly_1.36.0                
 [37] BSgenome_1.70.1                   limma_3.58.1                      rstudioapi_0.15.0                
 [40] RSQLite_2.3.4                     generics_0.1.3                    shape_1.4.6                      
 [43] BiocIO_1.12.0                     gtools_3.9.5                      ica_1.0-3                        
 [46] spatstat.random_3.2-2             googlesheets4_1.1.1               GO.db_3.18.0                     
 [49] Matrix_1.6-4                      ggbeeswarm_0.7.2                  fansi_1.0.6                      
 [52] S4Vectors_0.40.2                  abind_1.4-5                       R.methodsS3_1.8.2                
 [55] lifecycle_1.0.4                   yaml_2.3.8                        SummarizedExperiment_1.32.0      
 [58] rhdf5_2.46.1                      SparseArray_1.2.2                 BiocFileCache_2.10.1             
 [61] Rtsne_0.17                        blob_1.2.4                        promises_1.2.1                   
 [64] shinydashboard_0.7.2              crayon_1.5.2                      miniUI_0.1.1.1                   
 [67] lattice_0.22-5                    cowplot_1.1.1                     annotate_1.80.0                  
 [70] GenomicFeatures_1.54.1            KEGGREST_1.42.0                   pillar_1.9.0                     
 [73] knitr_1.45                        GenomicRanges_1.54.1              rjson_0.2.21                     
 [76] future.apply_1.11.0               codetools_0.2-19                  fastmatch_1.1-4                  
 [79] leiden_0.4.3.1                    glue_1.6.2                        data.table_1.14.10               
 [82] vctrs_0.6.5                       png_0.1-8                         spam_2.10-0                      
 [85] cellranger_1.1.0                  poweRlaw_0.70.6                   gtable_0.3.4                     
 [88] cachem_1.0.8                      xfun_0.41                         Signac_1.12.0                    
 [91] S4Arrays_1.2.0                    mime_0.12                         pracma_2.4.4                     
 [94] survival_3.5-7                    pbmcref.SeuratData_1.0.0          gargle_1.5.2                     
 [97] RcppRoll_0.3.0                    iterators_1.0.14                  statmod_1.5.0                    
[100] ellipsis_0.3.2                    fitdistrplus_1.1-11               ROCR_1.0-11                      
[103] nlme_3.1-164                      bit64_4.0.5                       progress_1.2.3                   
[106] filelock_1.0.3                    RcppAnnoy_0.0.21                  GenomeInfoDb_1.38.1              
[109] irlba_2.3.5.1                     vipor_0.4.5                       KernSmooth_2.23-22               
[112] seqLogo_1.68.0                    SeuratDisk_0.0.0.9021             colorspace_2.1-0                 
[115] BiocGenerics_0.48.1               DBI_1.1.3                         ggrastr_1.0.2                    
[118] tidyselect_1.2.0                  bit_4.0.5                         compiler_4.3.1                   
[121] curl_5.2.0                        hdf5r_1.3.8                       xml2_1.3.6                       
[124] DelayedArray_0.28.0               plotly_4.10.3                     rtracklayer_1.62.0               
[127] caTools_1.18.2                    scales_1.3.0                      lmtest_0.9-40                    
[130] rappdirs_0.3.3                    stringr_1.5.1                     digest_0.6.33                    
[133] goftest_1.2-3                     spatstat.utils_3.0-4              presto_1.0.0                     
[136] rmarkdown_2.25                    XVector_0.42.0                    htmltools_0.5.7                  
[139] pkgconfig_2.0.3                   MatrixGenerics_1.14.0             dbplyr_2.4.0                     
[142] fastmap_1.1.1                     ensembldb_2.26.0                  rlang_1.1.2                      
[145] GlobalOptions_0.1.2               htmlwidgets_1.6.4                 shiny_1.8.0                      
[148] farver_2.1.1                      zoo_1.8-12                        jsonlite_1.8.8                   
[151] BiocParallel_1.36.0               R.oo_1.25.0                       RCurl_1.98-1.13                  
[154] magrittr_2.0.3                    GenomeInfoDbData_1.2.11           dotCall64_1.1-1                  
[157] patchwork_1.1.3                   Rhdf5lib_1.24.0                   munsell_0.5.0                    
[160] Rcpp_1.0.11                       reticulate_1.34.0                 stringi_1.8.3                    
[163] zlibbioc_1.48.0                   MASS_7.3-60                       plyr_1.8.9                       
[166] parallel_4.3.1                    listenv_0.9.0                     ggrepel_0.9.4                    
[169] CNEr_1.38.0                       deldir_2.0-2                      Biostrings_2.70.1                
[172] splines_4.3.1                     tensor_1.5                        hms_1.1.3                        
[175] circlize_0.4.15                   BSgenome.Hsapiens.UCSC.hg38_1.4.5 igraph_1.6.0                     
[178] spatstat.geom_3.2-7               RcppHNSW_0.5.0                    reshape2_1.4.4                   
[181] biomaRt_2.58.0                    stats4_4.3.1                      TFMPvalue_0.0.9                  
[184] XML_3.99-0.16                     evaluate_0.23                     tzdb_0.4.0                       
[187] JASPAR2020_0.99.10                foreach_1.5.2                     httpuv_1.6.13                    
[190] RANN_2.6.1                        tidyr_1.3.0                       purrr_1.0.2                      
[193] polyclip_1.10-6                   SeuratData_0.2.2.9001             future_1.33.0                    
[196] clue_0.3-65                       scattermore_1.2                   xtable_1.8-4                     
[199] restfulr_0.0.15                   AnnotationFilter_1.26.0           RSpectra_0.16-1                  
[202] later_1.3.2                       googledrive_2.1.1                 tibble_3.2.1                     
[205] memoise_2.0.1                     beeswarm_0.4.0                    AnnotationDbi_1.64.1             
[208] GenomicAlignments_1.38.0          IRanges_2.36.0                    cluster_2.1.6                    
[211] globals_0.16.2                   `
