### ISSUE TITLE
fetus ref problem for mapping to reference

### ISSUE THREAD

**Issue by ERIGR** [satijalab/azimuth#127] opened 2022-09-28 14:51 UTC
Hi, 
this is the version of packages I used.
Session :
[1] Seurat_4.2.0       Azimuth_0.4.6      shinyBS_0.61.1     sp_1.5-0          
[5] SeuratObject_4.1.2 uwot_0.1.14

I get always the same error when trying to map my data to the human fetus reference (tried with several query dataset, always the same mistake).
Below, the code I run (query corresponds to any seurat object I tried)

query <- LoadFileInput(path = "TEST_110_GE_FILTERED_NON_NORMALIZED.rds")
query <- ConvertGeneNames(
  object = query,
  reference.names = rownames(x = reference$map),
  homolog.table = 'https://seurat.nygenome.org/azimuth/references/homologs.rds'
)

}

# Preprocess with SCTransform
query <- SCTransform(
  object = query,
  assay = "RNA",
  new.assay.name = "refAssay",
  residual.features = rownames(x = reference$map),
  reference.SCT.model = reference$map[["refAssay"]]@SCTModel.list$refmodel,
  method = 'glmGamPoi',
  ncells = 2000,
  n_genes = 2000,
  do.correct.umi = FALSE,
  do.scale = FALSE,
  do.center = TRUE
)

# Find anchors between query and reference
anchors <- FindTransferAnchors(
  reference = reference$map,
  query = query,
  k.filter = NA,
  reference.neighbors = "refdr.annoy.neighbors",
  reference.assay = "refAssay",
  query.assay = "refAssay",
  reference.reduction = "refDR",
  normalization.method = "SCT",
  features = intersect(rownames(x = reference$map), VariableFeatures(object = query)),
  dims = 1:50,
  n.trees = 20,
  mapping.score.k = 100
)

At this step, I get the error :
Error in index$getNNsByVectorList(query[x, ], k, search.k, include.distance) : 
  fv.size() != vector_size

I don't know where is the problem. Do you know what can be the problem ? The reference data were downloaded from Zenodo and md5sum were checked.

Thanks

**Comment by ERIGR** [comment] 2022-10-21 14:29
Hi, thanks for your answer. It allows me to run without error the code :

anchors <- FindTransferAnchors(
reference = reference$map,
query = query,
k.filter = NA,
reference.neighbors = "refdr.annoy.neighbors",
reference.assay = "refAssay",
query.assay = "refAssay",
reference.reduction = "refDR",
normalization.method = "SCT",
features = intersect(rownames(x = reference$map), VariableFeatures(object = query)),
dims = 1:50,
n.trees = 20,
mapping.score.k = 100
)

However, I get an error later in the following next step : 

refdata <- lapply(X = "annotation.l1", function(x) {
  reference$map[[x, drop = TRUE]]
})
names(x = refdata) <- "annotation.l1"
if (FALSE) {
  refdata[["impADT"]] <- GetAssayData(
    object = reference$map[['ADT']],
    slot = 'data'
  )
}
query <- TransferData(
  reference = reference$map,
  query = query,
  dims = 1:50,
  anchorset = anchors,
  refdata = refdata,
  n.trees = 20,
  store.weights = TRUE
)

# Calculate the embeddings of the query data on the reference SPCA
query <- IntegrateEmbeddings(
  anchorset = anchors,
  reference = reference$map,
  query = query,
  reductions = "pcaproject",
  reuse.weights.matrix = TRUE
)

# Calculate the query neighbors in the reference
# with respect to the integrated embeddings
query[["query_ref.nn"]] <- FindNeighbors(
  object = Embeddings(reference$map[["refDR"]]),
  query = Embeddings(query[["integrated_dr"]]),
  return.neighbor = TRUE,
  l2.norm = TRUE
) 

At this step, I get again the error :
Computing nearest neighbors
Error in index$getNNsByVectorList(query[x, ], k, search.k, include.distance) : 
  fv.size() != vector_size

Do you know what can be the problem with this step ?

Thanks

**Comment by denizff** [comment] 2023-02-27 10:52
I had the same error with a reference of my own.
The problem is the number of PCs your reference has and the number of PCs you used to get refdr.annoy.neighbors.
It should be the same to make it work.

So I checked the code for RunAzimuth() and I changed some of the parameters myself to adapt it to the number of dimensions for the neighbors

dims <- as.double(slot(reference, "neighbors")$[refdr.annoy.neighbors@alg.info](mailto:refdr.annoy.neighbors@alg.info)$ndim)

query[["query_ref.nn"]] <- FindNeighbors(object = Embeddings(reference[["refDR"]])[,1:dims],
query = Embeddings(query[["integrated_dr"]]),
return.nghbor = TRUE,
l2.norm = TRUE,
verbose = F )

Best regards,

Deniz Fettahoglu

**Comment by Gesmira** [comment] 2023-02-27 16:55
Hi Deniz, thank you for looking into this bug! I'm looking into this now.
@ERIGR could you include the code you used when you created your azimuth reference? Did you also set the `dims` parameter to less than the number of PCs in refDR?

**Comment by ERIGR** [comment] 2023-02-28 08:11
Hello,

sorry I am on vacation with no access to my professional computer. Besides, I didn't work on this problem since at least one month. I answer you as soon as possible.

Thank for you help.


________________________________
De : gesmira ***@***.***>
Envoyé : lundi 27 février 2023 17:55:54
À : satijalab/azimuth
Cc : ROBERT Elie; Mention
Objet : Re: [satijalab/azimuth] fetus ref problem for mapping to reference (Issue #127)


Hi Deniz, thank you for looking into this bug! I'm looking into this now.
@ERIGR<https://github.com/ERIGR> could you include the code you used when you created your azimuth reference? Did you also set the dims parameter to less than the number of PCs in refDR?

**Comment by denizff** [comment] 2023-02-28 08:22
For example, my ref data has 30 PCs. I used the first 13 PCs to run FindNeighbors() and RunUmap()

Then I made a reference with still the first 13 PCs to get the same neighbors :

ref <- AzimuthReference(object = data,
refDR = "pca",
refAssay = "integrated",
refUMAP = "umap",
metadata = "clusters",
dims= 1:13)

After that, I used it with RunAzimuth :

options(Azimuth.map.ndims = 13)
query_projected <- RunAzimuth(query, "path_to_ref", do.adt = FALSE)

and I had the following error :

Error in index$getNNsbyVectorList(query[x,], k, search.k, include.distance) : fv.size() != vector_size

So I checked thourougly the code for RunAzimuth and I found out that the problem was with dims = 13 when I made the reference.
The neighbors were calculated with the first 13 PCs.
But in RunAzimuth code the dims variable takes as a value the length of the refDR which is 30 here :

dims <- as.double(length(slot(reference, "reductions")$refDR))

Because of that, there are errors in FindTransferAnchors and FindNeighbors where dims is set to 30 and not 13 the number of PCs used in the reference for FindNeighbors.

So I made the changes above concerning dims and FindNeighbors() in RunAzimuth() and it worked.

**Comment by Gesmira** [comment] 2023-04-19 00:33
Hi, thanks to @denizff's suggestions, this is now fixed n the `seurat5` branch of Azimuth and will be merged into the master branch soon. For details in installing seurat5 packages, see here: https://satijalab.org/seurat/articles/install.html

**Closed by Gesmira** 2023-04-19 00:33 UTC
